### ISSUE TITLE
Issue appears as solved but it is not.

### ISSUE THREAD

**Issue by hugoheml** [mehatab/fettle#16]
**Describe the bug**
When an issue is created, it appears to be closed when it is not.

**To Reproduce**
1. Create an issue with `incident` tag.
2. Go on your status page and check the issue description.

**Expected behavior**
Either the description of the problem (the description of the outcome) or indicate that the issue is currently being resolved.

**Screenshots**
![image](https://github.com/mehatab/fettle/assets/51268820/5106e591-2cd3-4f99-b53a-d758d770d7aa)

**Comment by mehatab** [comment]
closing this issue as resolved
