### ISSUE TITLE
Followed the instructions but status is empty

### ISSUE THREAD

**Issue by ddt3** [mehatab/fettle#17]
**Describe the bug**
On my status page https://status.familie-dokter.net/ it says "Partial Outage"  although the healthcheck returns success:
https://github.com/ddt3/server-status/blob/main/public/status/Redgrendel_report.log

This might be very much related to my inexperience with the Workflow and Actions (see below)

**To Reproduce**
Not sure where I went wrong...

**Expected behavior**
The status overview should match the actual status

**Screenshots**
![image](https://github.com/mehatab/fettle/assets/6237282/79f7da93-f40c-48c3-81a2-49a886d7dcd0)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser [e.g. chrome, safari]: Chrome, Firefox, Edge

**Additional context**
I forked the repository and followed the instructions. As this was my first time to use Actions and Workflows I needed a bit more guidance than the one provide in the readme. Also some other things are assumed to need change, but are not mentioned.
Eg instruction does not mention that:
- Workflow access to the repository is needed
- Cname needs to be changed
- Healthchek is are committed to repo as  mehatab-fettle (is it supposed to be like that?)

I came across your status solution on google,really like it and also like the fact that it offers me  a first use of actions. 

I might be an  idiot for not understanding all this, still I hope you can help me make this status overview work

Thank you!

**Comment by mehatab** [comment]
I apologise for the oversight. It appears I forgot to include an additional step in the documentation. Kindly follow the steps below to resolve the issue:

**Service Status URL Update**

1. Open the src > services > hooks > useServices.tsx file.
2. Locate the URL and update it with your repository URL.
3. Replace mehatab/fettle with your own username/repo-name.

`https://raw.githubusercontent.com/mehatab/fettle/main/public/status/${key}_report.log`

1. Similarly, open the src > services > hooks > useSystemStatus.tsx file.
4. Update the URL with your repository URL.
5. Replace mehatab/fettle with your own username/repo-name.

`https://raw.githubusercontent.com/mehatab/fettle/main/public/status/${key}_report.log`

These changes will be reflected in the updated documentation. Thank you for bringing this to our attention.

**Comment by ddt3** [comment]
Thank you! Feel a bit silly for not spotting that myself but it works beautifully now .
